version: "3.7"
services:
  app:
    build:
      args:
        user: bruno
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: jsonresume-manager
    container_name: jsonresume-manager-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - jsonresume-manager

  db:
    image: mysql:5.7
    container_name: jsonresume-manager-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - jsonresume-manager
  node:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run watch"

  nginx:
    image: nginx:alpine
    container_name: jsonresume-manager-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - jsonresume-manager

networks:
  jsonresume-manager:
    driver: bridge
